"""LLM-powered fix proposer for ClawLite AutoImprove.

Generates fix proposals for any issue type using LLM analysis.
"""

import json
import logging
import re
from dataclasses import dataclass
from typing import List, Dict, Any, Optional
from pathlib import Path
import requests

logger = logging.getLogger('autoimprove.fixer.llm_proposer')

# Fix proposal prompt
FIX_PROPOSAL_PROMPT = """You are a senior developer improving an AI assistant called ClawLite.

## Issue Detected:
- **Type:** {issue_type}
- **Severity:** {severity}
- **Description:** {description}
- **Evidence:** {evidence}
- **Context:** {context}

## ClawLite Architecture:
- `src/agent.py` - Main agent loop, tool calling, iteration limits
- `src/llm.py` - LLM provider abstraction, API calls, error handling
- `src/tools.py` - Tool definitions and implementations
- `prompts/system.md` - System prompt (personality, rules, constraints)
- `prompts/AGENTS.md` - Agent behavior guidelines
- `config.yaml` - Runtime configuration

## Your Task:
Propose a specific fix for this issue. Be concrete - provide actual code or text changes.

## Output Format (JSON):
{{
  "fix_type": "code|prompt|config|architecture",
  "target_file": "path/to/file.py or prompts/system.md",
  "description": "What this fix does",
  "rationale": "Why this will solve the issue",
  "changes": [
    {{
      "action": "replace|insert|append",
      "location": "function name, line number, or section",
      "old_text": "text to find (for replace)",
      "new_text": "new text to insert"
    }}
  ],
  "test_suggestion": "How to verify the fix works",
  "risk_level": "low|medium|high",
  "requires_review": true
}}

Be specific and actionable. Output ONLY the JSON object."""


@dataclass
class LLMFixProposal:
    """Fix proposal generated by LLM."""
    issue_type: str
    fix_type: str
    target_file: str
    description: str
    rationale: str
    changes: List[Dict[str, str]]
    test_suggestion: str
    risk_level: str
    requires_review: bool = True
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'issue_type': self.issue_type,
            'fix_type': self.fix_type,
            'target_file': self.target_file,
            'description': self.description,
            'rationale': self.rationale,
            'changes': self.changes,
            'test_suggestion': self.test_suggestion,
            'risk_level': self.risk_level,
            'requires_review': self.requires_review,
        }


class LLMProposer:
    """Generates fix proposals using LLM."""
    
    def __init__(self, base_url: str, model: str, timeout: int = 120):
        self.base_url = base_url.rstrip('/')
        self.model = model
        self.timeout = timeout
    
    def _call_llm(self, prompt: str) -> Optional[str]:
        """Call LLM API and return response."""
        try:
            response = requests.post(
                f"{self.base_url}/chat/completions",
                json={
                    "model": self.model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.3,
                    "max_tokens": 2000,
                },
                timeout=self.timeout,
            )
            response.raise_for_status()
            data = response.json()
            
            msg = data['choices'][0]['message']
            content = msg.get('content', '')
            if not content:
                content = msg.get('reasoning_content', '')
            
            return content
        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            return None
    
    def _parse_response(self, response: str) -> Optional[Dict]:
        """Parse JSON from LLM response."""
        if not response:
            return None
        
        strategies = [
            lambda r: json.loads(r.strip()),
            lambda r: json.loads(re.search(r'```json\s*(.*?)\s*```', r, re.DOTALL).group(1)) if "```json" in r else None,
            lambda r: json.loads(re.search(r'```\s*(.*?)\s*```', r, re.DOTALL).group(1)) if "```" in r else None,
            lambda r: json.loads(re.search(r'\{.*\}', r, re.DOTALL).group(0)),
        ]
        
        for strategy in strategies:
            try:
                result = strategy(response)
                if result and isinstance(result, dict):
                    return result
            except:
                continue
        
        logger.warning("Failed to parse LLM response as JSON")
        return None
    
    def propose_fix(self, issue: Any) -> Optional[LLMFixProposal]:
        """Generate a fix proposal for an issue."""
        # Format context
        context = ""
        if hasattr(issue, 'context') and issue.context:
            context = json.dumps(issue.context, indent=2)
        
        evidence = ""
        if hasattr(issue, 'context'):
            evidence = issue.context.get('evidence', '') or issue.context.get('claim', '')
        if not evidence and hasattr(issue, 'exchange'):
            evidence = f"User: {issue.exchange.user_message[:200]}\nAssistant: {issue.exchange.assistant_response[:200]}"
        
        prompt = FIX_PROPOSAL_PROMPT.format(
            issue_type=issue.type,
            severity=issue.severity,
            description=issue.description,
            evidence=evidence,
            context=context,
        )
        
        logger.info(f"Generating fix proposal for issue: {issue.type}")
        response = self._call_llm(prompt)
        
        if not response:
            return None
        
        data = self._parse_response(response)
        if not data:
            return None
        
        try:
            proposal = LLMFixProposal(
                issue_type=issue.type,
                fix_type=data.get('fix_type', 'prompt'),
                target_file=data.get('target_file', 'prompts/system.md'),
                description=data.get('description', ''),
                rationale=data.get('rationale', ''),
                changes=data.get('changes', []),
                test_suggestion=data.get('test_suggestion', ''),
                risk_level=data.get('risk_level', 'medium'),
                requires_review=data.get('requires_review', True),
            )
            logger.info(f"Generated fix proposal: {proposal.description[:100]}")
            return proposal
        except Exception as e:
            logger.error(f"Failed to create proposal: {e}")
            return None


def propose_fix_with_llm(issue: Any, config: Dict) -> Optional[LLMFixProposal]:
    """Generate a fix proposal for any issue type using LLM."""
    llm_config = config.get('vllm', {})
    proposer = LLMProposer(
        base_url=llm_config.get('url', 'http://localhost:8080/v1'),
        model=llm_config.get('model', 'default'),
        timeout=llm_config.get('timeout', 120),
    )
    return proposer.propose_fix(issue)


def save_proposals_to_backlog(proposals: List[LLMFixProposal], backlog_path: Path):
    """Save LLM-generated proposals to backlog file."""
    if not proposals:
        return
    
    with open(backlog_path, 'a') as f:
        for proposal in proposals:
            f.write(f"\n\n### {proposal.issue_type} (LLM-generated)\n")
            f.write(f"**Fix Type:** {proposal.fix_type}\n")
            f.write(f"**Target:** {proposal.target_file}\n")
            f.write(f"**Description:** {proposal.description}\n")
            f.write(f"**Rationale:** {proposal.rationale}\n")
            f.write(f"**Risk:** {proposal.risk_level}\n")
            f.write(f"**Status:** ⏳ Awaiting approval\n")
            
            if proposal.changes:
                f.write("\n**Changes:**\n```\n")
                for change in proposal.changes:
                    f.write(f"- {change.get('action', 'modify')}: {change.get('location', 'unknown')}\n")
                    if change.get('new_text'):
                        f.write(f"  + {change['new_text'][:200]}...\n")
                f.write("```\n")
            
            f.write(f"\n**Test:** {proposal.test_suggestion}\n")
    
    logger.info(f"Saved {len(proposals)} LLM proposals to backlog")
